INSERT INTO clientes (cd_cliente, ds_nome, ds_cidade, cd_uf) VALUES
(1, 'Maria Silva', 'Curitiba', 'PR'),
(2, 'João Souza', 'Londrina', 'PR'),
(3, 'Ana Pereira', 'Maringá', 'PR'),
(4, 'José Oliveira', 'Ponta Grossa', 'PR'),
(5, 'Antônio Lima', 'Cascavel', 'PR'),
(6, 'Francisca Rodrigues', 'São José dos Pinhais', 'PR'),
(7, 'Carlos Alves', 'Foz do Iguaçu', 'PR'),
(8, 'Paulo Ferreira', 'Colombo', 'PR'),
(9, 'Pedro Santos', 'Guarapuava', 'PR'),
(10, 'Lucas Gonçalves', 'Paranaguá', 'PR'),
(11, 'Marcos Gomes', 'Florianópolis', 'SC'),
(12, 'Rafael Costa', 'Joinville', 'SC'),
(13, 'Fernanda Ribeiro', 'Blumenau', 'SC'),
(14, 'Sandra Martins', 'São José', 'SC'),
(15, 'Daniel Carvalho', 'Chapecó', 'SC'),
(16, 'Leonardo Almeida', 'Criciúma', 'SC'),
(17, 'Beatriz Pinto', 'Itajaí', 'SC'),
(18, 'Mariana Araújo', 'Jaraguá do Sul', 'SC'),
(19, 'Ricardo Melo', 'Palhoça', 'SC'),
(20, 'Tiago Barbosa', 'Lages', 'SC'),
(21, 'Camila Castro', 'São Paulo', 'SP'),
(22, 'Matheus Dias', 'Guarulhos', 'SP'),
(23, 'Gabriel Fernandes', 'Campinas', 'SP'),
(24, 'Felipe Azevedo', 'São Bernardo do Campo', 'SP'),
(25, 'Julia Teixeira', 'Santo André', 'SP'),
(26, 'Eduardo Correia', 'Osasco', 'SP'),
(27, 'Gustavo Moreira', 'São José dos Campos', 'SP'),
(28, 'Bruno Mendes', 'Ribeirão Preto', 'SP');

INSERT INTO produtos (cd_produto, ds_descricao, vl_preco_venda) VALUES
(1, 'Caneta esferográfica azul', 1.50),
(2, 'Lápis preto HB', 0.75),
(3, 'Borracha branca', 0.50),
(4, 'Apontador', 0.80),
(5, 'Caderno universitário 200 folhas', 15.00),
(6, 'Agenda anual', 12.00),
(7, 'Marcador de texto amarelo', 2.00),
(8, 'Corretivo líquido', 3.50),
(9, 'Régua 30cm', 1.20),
(10, 'Tesoura escolar', 4.00),
(11, 'Cola branca 90g', 2.50),
(12, 'Papel sulfite A4 pacote 500 folhas', 20.00),
(13, 'Bloco adesivo', 5.00),
(14, 'Pastas plásticas', 2.00),
(15, 'Clips para papel', 1.00),
(16, 'Grampeador', 10.00),
(17, 'Refil para grampeador', 1.50),
(18, 'Caneta marca-texto', 2.50),
(19, 'Calculadora simples', 25.00),
(20, 'Caneta hidrográfica', 3.00),
(21, 'Lápis de cor 12 cores', 8.00),
(22, 'Pincel atômico', 3.50),
(23, 'Fita adesiva transparente', 1.80),
(24, 'Envelope pardo', 0.60),
(25, 'Folhas pautadas', 4.00),
(26, 'Papel cartão', 2.20),
(27, 'Cartolina branca', 1.00),
(28, 'Pasta catálogo', 6.00),
(29, 'Livro de registro', 12.00),
(30, 'Crachá plástico', 0.90);